- src/components/Time.js
- src/utils/recTime.js
everything should be identical on the front-end except that times like 8.5 seconds (when displayed using mili seconds) will show up as 8,500 and not 08,500 as it used to be. Times in hundreds used to show up as 8,50, and will continue to show up like this. The fix was to address the total time (and time played for death, esc, etc.) on the personal stats page, which when it was greater than 60 hours or so, did not display correctly. It would show something like 4:3423:34,50 which would mean 4 hours, 3423 minutes, 34 seconds, etc. Should now be fixed.
> re-factor and fix Time component for input > 60 hours

- src/components/LeaderHistory.js
- src/pages/level/StatsTable.js
- src/pages/level/index.js
- src/pages/level/store.js
- new tab `Leaders`
- adds also personal leader history to `Personal Stats` tab
> feat(levels): add leader history for level

- src/pages/battle/LevelStatsContainer.js
puts scroll bar on table instead of the page on mobile.
> fix(battle): overflow auto in battle results table

- src/components/Stars.js
- src/features/ReplayRating/index.js
Was just going to fix text alignment, but then Ismo mentioned this existed so I did some more things:
- Refactor Stars component to use [the MUI Rating component](https://material-ui.com/components/rating/)
- Fixes potential bug with this code: `+average.toFixed(2)` (unclear if this was intended or not). I think the idea was to force the `average` to be a number so that you could use `.toFixed()` on it? In which case it was a bug, since it would try to do `.toFixed()` first, then cast the resulting string back to a number. Though isn't it always a number anyway? 🤷‍♀️Not sure if any of this is necessary in the first place
- Vertically aligns the average rating text with the star icons
- Disables voting until you get the data for the actual replay
> refactor(ui): use MUI Rating component for Stars

- src/features/ReplayRating/index.js
I introduced a new bug and there was already a previous bug present 🤐
This should properly check that we have the correct replay and get ratings when it changes. Previously moving from replay to replay would never update the ratings because of the useEffect missing dependency.
Still feels really hacky and dumb though...
> fix(ui): replay rating vote bug

- src/features/ReplayComments/index.js
I actually thought the previous logic made sense because the effect would re-run every time component gets mounted, but for some reason it sometimes does not run when navigating to other replays, i don't know why. It's intermittent but you if you click enough replays on live site you'll see its often broken due to not re-running the network request.
> fix(replayComments): don't show comments from last rec

- src/components/Names.js
- src/components/RecentRecords.js
- src/features/ReplayList/index.js
- src/pages/home/cards/BattlesCard.js
- src/pages/home/cards/RecordsCard.js
- src/pages/kuski/Records.js
- src/pages/kuski/index.js
- src/pages/levelpack/index.js
- src/pages/levels/LevelpacksDetailed.js
- src/pages/levels/index.js
- src/pages/levels/store.js
- src/react-query.js
- src/router.js
- levelpack archive works on mobile
- adjusted formula for levelpack archive popularity bar to reflect production database
- levelpack archive detailed view works better on mobile (and no longer lists more than 2 top kuski's)
- home page recent records has more clear title and re-worked columns.
- player records page has attempts column added, and sort by time (high/low) options.
- sort option for player records page stored in URL instead of component state.
> feat(levelstats): various small improvements

- src/features/ReplayCommentArchive/index.js
put things into 2 columns instead of 4. arguably a bit nicer to look at and understand.
> feat(replay-comments-archive): display nicer

- src/pages/search/index.js
AddedBy is 0 for a small number of levels with no runs.
> fix(search): fix broken level search when there is no AddedBy info

- src/pages/kuski/Preview.js
- src/pages/level/LevelInfoLevelStats.js
- src/pages/level/StatsTable.js
- src/pages/levels/Controls.js
- src/pages/levels/LevelpacksDetailed.js
Also make the finish type labels and ordering more consistent across pages.
Fixes https://github.com/elmadev/elmaonline-site/issues/566
> fix(levelpacks): fix swapped dead and esced labels

- src/components/Welcome.js
- src/pages/help/tabs/HowToInstall.js
- Updated the Game link, since Game name has changed from **Elasto Mania** to **Elasto Mania Remastered** (_appid_ is same)
- Added `target="_blank"` and `rel="noreferrer"` to those _anchor tags_ so they **Open in New Tab**
> Fixed Game link & Updated links to open in New Tab

- src/components/CupCurrent.js
added ".lev" to the previous link which downloads the level. Then if the level isn't hidden we'll show a link to level page.
> feat(home): level page link for ongoing events

- src/pages/cup/Team.js
used to only work when you started on another tab, because it would fetch the cup object in some other request. Now if you refresh the page or click on a link directly to the tab, the events and replays will properly get loaded.
> fix(cup): team tab loads events when navigating directly to it

- src/components/RecentRecords.js
- src/pages/levels/RecordsCard.js
- src/pages/levels/index.js
- src/router.js
The feature used to be on the homepage but then we scrapped it cuz it didn't really make too much sense. I added it back as a tab under levels this time (because I'm not sure where else really).
Since it's no longer a compact card, I added a few more columns.
Maybe we can test it out here and see how it goes. I thought maybe ordering by kuski's played instead of total playtime might be good. I think that might require a change to the back-end though. Maybe we can ask for some player feedback and then decide later.
> Add back recent top records card (as a sub page of levels this time)

- src/components/Recplayer.js
- src/features/ReplaySettings/store.js
- src/pages/settings/DeviceSettings.js
- src/pages/settings/index.js
- src/pages/settings/store.js
Since there are some different recplayers across the site, and not all have settings icon underneath them, I added a new tab for device settings, which can be viewed when not logged in. It has the single setting for now to adjust the scale of the recplayer zoom on page load. So you can set it to 50% for example to be twice as zoomed out as normal when the page loads with a replay in it. I added this because I feel like I prefer battle recs to be more zoomed on mobile, but it's not easy to choose one number that suits all.
In the future we could add the zoom scale input to the RecplaySettings component, and then add the settings component to the different recplayer instances.
Also, people not logged in will have a hard time finding this setting. We could maybe add a Settings icon next to …
> Add device settings tab and replay viewer default zoom scale

- src/api.js
- src/features/ReplayCommentArchive/index.js
- src/features/ReplayCommentArchive/store.js
Added pagination and added page number as url parameter.
Since we recently imported many thousands of replays and comments, there are now a lot and it makes the production site quite slow when it queries all at once. So now it just fetches one page at a time from the server.
> feat(replay-comments): add pagination

- src/pages/level/StatsTable.jsx
First/last played dates will now include spied runs as well.
> fix(levels): Fix personal stats tab crashing with only spied runs

- src/features/LevelMap/index.jsx
Closes https://github.com/elmadev/elmaonline-site/issues/671
Before:
After:
> fix(levels): fix empty space next to unfancy level map on level page

- src/api.js
- src/components/CupCurrent.jsx
- src/components/Popularity.jsx
- src/components/Preview.jsx
- src/easypeasy.js
- src/features/LevelCollectionStats/index.jsx
- src/features/LevelCollectionStats/store.js
- src/features/RankingTable/index.jsx
- src/features/ReplayList/index.jsx
- src/pages/cup/PlayStats.jsx
- src/pages/cup/index.jsx
- src/pages/level/index.jsx
- src/pages/levelpack/PlayStats.jsx
- src/pages/levelpack/index.jsx
- src/utils/calcs.js
- src/utils/format.js
Adds 2 new pages...
Level pack play stats, and Cup play stats.
I didn't put too much thought into the stats or how they are displayed for now (just lots of "popularity" bars). But we could modify some things later.
> play stats tabs for level packs and cups

- src/features/LevelList/index.jsx
If result has less levels than `pageSize`, show number of levels in pagination (next page button will be disabled automatically).
> fix(levels): show correct number of levels in search pagination
