elmadev/elmaonline-web

- .gitignore
- src/components/TopBar.js
- src/pages/battle/LevelStatsContainer.js
- src/pages/battle/RecView.js
- src/pages/battle/RightBarContainer.js
> Battle page mobile

- src/pages/help/index.js
- src/pages/help/tabs/Crew.js
- src/pages/help/tabs/Donate.js
- src/pages/help/tabs/EolFolder.js
- src/router.js
added links such as /help/eolconfiguration or /help/eolfiles/lev
> add help page section routing

- src/pages/levelpack/index.js
- src/pages/levels/index.js
- src/router.js
> feat(levels): routing for levels/collections and /levels/packs/:tab

- src/pages/battle/RightBarContainer.js
- src/pages/search/index.js
Battles by designer tried to access non-existent LevelData for 1h TT.
> fix(battles): fix 1h TT display on search results and battle page

- src/api.js
- src/components/Field.js
- src/components/FormResponse.js
- src/pages/levelpack/Admin.js
- src/pages/levelpack/UpdateForm.js
- src/pages/levelpack/index.js
- src/pages/levelpack/store.js
- src/utils/easy-peasy.js
https://user-images.githubusercontent.com/24510397/112907497-f6460480-90bb-11eb-9d20-51984aa8af78.mp4
> feat(levelpack): update long name / desc after insert

- src/components/Containers.js
- src/components/FieldBoolean.js
- src/components/List.js
- src/components/RecListItem.js
- src/components/Recplayer.js
- src/components/Stars.js
- src/easypeasy.js
- src/features/RecList/index.js
- src/features/ReplayRating/index.js
- src/features/ReplaySettings/index.js
- src/features/ReplaySettings/store.js
- src/pages/replay/index.js
- src/pages/replay/store.js
- src/router.js
- src/theme.js
Closes https://github.com/elmadev/elmaonline-site/issues/433
> Replay page improvements

- src/api.js
- src/pages/kuski/KuskiHeader.js
- src/pages/kuski/index.js
- src/pages/kuski/store.js
int total time takes .2s on dev now. Not sure what that will be on live but will be many times faster for sure.
> feat(profile): optimize int tt

- src/components/Time.js
> fix(Time): show apples

- src/components/RankingValue.js
- src/pages/battle/LevelStatsContainer.js
- src/theme.js
looks like this (on pink theme)
> feat(battle): show ranking +/- beside ranking

- src/api.js
- src/features/ReplayList/index.js
- src/pages/levelpack/index.js
Fixes https://github.com/elmadev/elmaonline-site/issues/487
> feat(levelpacks): add replays tab

- src/pages/help/tabs/GameUpdates.js
- src/pages/help/tabs/gameupdates.json
Also add a Download text to the update headlines to make downloading more intuitive.
> feat(help): add 1.0.13 game update info

- src/pages/levels/Controls.js
> feat(levelpacks): show sort on non-detailed view

- src/components/CupWidget.js
- src/pages/cup/store.js
https://github.com/elmadev/elmaonline-site/pull/544
> feat(home): show multiple ongoing cups/events

- package.json
- src/pages/battles/Search.js
- yarn.lock
hopefully this does the job. prod would need "yarn" run to downgrade dependency.
> fix(battle-search): pagination/per-page, and mobile

- src/pages/level/index.js
- src/pages/level/store.js
cleaned up a mess that I previously created in the store.
> refactor(level): move crippled queries to react-query

- src/pages/levels/Controls.js
- src/pages/levels/storeUtils.js
Closes: [#513](https://github.com/elmadev/elmaonline-site/issues/513)
> feat(levelpacks): add option to sort levelpacks by created

- src/pages/level/StatsTable.js
Fixes https://github.com/elmadev/elmaonline-site/issues/567
> fix(levels): fix level personal stats tab crashing

- src/features/Notifications/index.js
Frontend changes only so far
Closes: 573 @ elmaonline-site
> feat(kuskis): add pagination to notification list

- src/pages/levelpack/Kinglist.js
Simple record count thingy for king list
Closes: 572 @ elmaonline-site
> feat(levelpacks): add record count to king list

- src/api.js
- src/pages/levelpack/RecordHistory.js
- src/pages/levelpack/index.js
I guess just let me know if you would prefer I use easy peasy for fetching the data.
> Levelpack record history

- src/api.js
- src/pages/level/index.jsx
- src/pages/level/store.js
Needs https://github.com/elmadev/elmaonline-site/pull/634 to work.
Closes https://github.com/elmadev/elmaonline-site/issues/624
> feat(levels): add date range filter to personal stats

- src/pages/replay/index.jsx
- src/pages/replay/store.js
Backend change https://github.com/elmadev/elmaonline-site/pull/636
> feat(replays): add edit tags

- src/pages/replay/index.jsx
Comment and Unlisted can still only be edited by the uploader.
Needs https://github.com/elmadev/elmaonline-site/pull/649
> feat(replays): Allow mods to edit replay tags and DrivenBy

- src/components/Preview.jsx
- src/components/Recplayer.jsx
- src/pages/battle/RecView.jsx
- src/pages/battle/RightBarContainer.jsx
- src/pages/cup/Personal.jsx
- src/pages/cup/Team.jsx
- src/pages/kuski/Preview.jsx
- src/pages/replay/index.jsx
This passes the main replay shirt to recplayer everywhere
> pass shirts to recplayer

- src/components/Recplayer.jsx
- src/pages/battle/RecView.jsx
> fix(battle): start battle recs from beginning

- src/components/TagFilter.jsx
- src/features/RecList/index.jsx
- src/features/ReplayList/index.jsx
- src/pages/level/index.jsx
- src/pages/replay/index.jsx
https://github.com/user-attachments/assets/86b5cae0-5123-46b8-b98f-92e5e3b14633
Closes https://github.com/elmadev/elmaonline-site/issues/646
> Replay list improvements

- src/components/LevelCard.jsx
- src/features/LevelList/index.jsx
- src/features/LevelList/store.js
- grid view
- search params in url
- sort results asc/desc toggle
- search box responsiveness etc. improvements
> feat(levels): level search improvements

- src/pages/kuski/Preview.jsx
- src/pages/level/index.jsx
Part of https://github.com/elmadev/elmaonline-site/issues/711
> feat(levels): preview replays from personal leader history

- src/api.js
- src/pages/cup/Personal.jsx
- src/pages/cup/store.js
- add also possibility to watch replays for all personal runs in current events
> feat(cups): show apple runs in personal tab

- src/pages/battle/RightBarContainer.jsx
Before:
After:
Suggested by Isti in Discord. 👍 from multiple ppl.
> feat(replays): tune "go to replay/level" button styles
